import { StyleSheet } from 'react-native';

import { designSystem } from '@/constants/design-system';

export const styles = StyleSheet.create({
  managerListPanel: {
    flex: 1,
    minHeight: 0,
  },
  managerListHeader: {
    alignItems: 'center',
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  managerListTitleBlock: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  managerListTitle: {
    color: designSystem.colors.ink,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  managerListMeta: {
    color: designSystem.colors.mutedText,
    fontSize: 11,
    lineHeight: 15,
  },
  compactCreateButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.lime,
    borderRadius: 14,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: 10,
  },
  compactCreateButtonText: {
    color: designSystem.colors.darkGreen,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  inventoryHeaderRow: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 30,
    paddingHorizontal: 12,
  },
  inventoryHeaderText: {
    color: designSystem.colors.subtleText,
    fontSize: 9,
    fontWeight: '800',
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  inventoryListingColumn: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  inventoryMetricColumn: {
    flexShrink: 0,
    textAlign: 'right',
    width: 52,
  },
  managerDetailPanel: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    width: 'auto',
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.lime,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  addButtonText: {
    color: designSystem.colors.darkGreen,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  resourceList: {
    gap: 0,
    padding: 0,
  },
  resourceItem: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    minHeight: 58,
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'relative',
  },
  resourceSelectedRail: {
    backgroundColor: designSystem.colors.darkGreen,
    borderRadius: 2,
    bottom: 9,
    left: 0,
    position: 'absolute',
    top: 9,
    width: 3,
  },
  resourceImage: {
    borderRadius: 6,
    height: 40,
    width: 40,
  },
  resourceCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  resourceTitle: {
    color: designSystem.colors.ink,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 17,
  },
  resourceSubtitle: {
    color: designSystem.colors.mutedText,
    fontSize: 10,
    lineHeight: 14,
  },
  inventoryCellText: {
    color: designSystem.colors.ink,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  detailArea: {
    borderRadius: 12,
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  detailContent: {
    flex: 1,
    minHeight: 0,
  },
  detailHeader: {
    alignItems: 'center',
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailHeroImage: {
    borderRadius: 8,
    height: 82,
    width: 112,
  },
  detailHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  detailTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailEyebrow: {
    color: designSystem.colors.darkGreen,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: designSystem.colors.ink,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
  },
  detailSubtitle: {
    color: designSystem.colors.warmDark,
    fontSize: 12,
    lineHeight: 16,
  },
  detailStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
    maxWidth: 420,
  },
  detailMetric: {
    borderColor: designSystem.colors.borderSoft,
    borderRadius: 8,
    borderWidth: 1,
    gap: 1,
    minWidth: 78,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  detailMetricValue: {
    color: designSystem.colors.ink,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 18,
  },
  detailMetricLabel: {
    color: designSystem.colors.mutedText,
    fontSize: 9,
    fontWeight: '800',
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.lime,
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 12,
  },
  saveButtonText: {
    color: designSystem.colors.darkGreen,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  disabledButton: {
    opacity: 0.55,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: designSystem.colors.mutedText,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  detailTabs: {
    flexGrow: 0,
    flexShrink: 0,
    maxHeight: 48,
  },
  detailTabsContent: {
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  detailTab: {
    minHeight: 30,
    minWidth: 84,
  },
  detailScroller: {
    flex: 1,
  },
  detailBody: {
    gap: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  sectionStack: {
    gap: 14,
  },
  editorStack: {
    gap: 16,
  },
  friendlySection: {
    borderColor: designSystem.colors.borderSoft,
    borderRadius: 8,
    borderWidth: 1,
    gap: 9,
    overflow: 'hidden',
    paddingTop: 0,
  },
  friendlySectionTitle: {
    backgroundColor: designSystem.colors.scrimFaint,
    color: designSystem.colors.ink,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 19,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  friendlySubsectionTitle: {
    color: designSystem.colors.subtleText,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
    paddingTop: 4,
    textTransform: 'uppercase',
  },
  friendlyTable: {
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  friendlyRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    minHeight: 34,
    paddingVertical: 2,
  },
  friendlyLabel: {
    color: designSystem.colors.subtleText,
    flexShrink: 0,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
    paddingTop: 3,
    textTransform: 'uppercase',
    width: 160,
  },
  friendlyInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    minHeight: 22,
    padding: 0,
  },
  friendlyInputMultiline: {
    minHeight: 54,
    textAlignVertical: 'top',
  },
  derivedValueText: {
    color: designSystem.colors.ink,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    minHeight: 22,
  },
  derivedValueStack: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  derivedRateText: {
    color: designSystem.colors.gray,
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 15,
  },
  priceCell: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  currencyPrefix: {
    color: designSystem.colors.darkGreen,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  priceInput: {
    flex: 0,
    minWidth: 72,
  },
  capacityCell: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  stepperCell: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  stepperButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 13,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  stepperButtonText: {
    color: designSystem.colors.darkGreen,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 18,
  },
  stepperInput: {
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
    minWidth: 34,
    padding: 0,
    textAlign: 'center',
  },
  stepperSuffix: {
    color: designSystem.colors.mutedText,
    fontSize: 12,
    lineHeight: 16,
  },
  friendlyListBlock: {
    gap: 8,
  },
  commaPreviewWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 8,
    paddingLeft: 172,
  },
  commaPreviewChip: {
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 14,
    minHeight: 28,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  commaPreviewText: {
    color: designSystem.colors.ink,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  tripFitList: {
    gap: 0,
    paddingBottom: 12,
  },
  tripFitTableHeader: {
    alignItems: 'center',
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    minHeight: 34,
    paddingVertical: 6,
  },
  tripFitRow: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    minHeight: 46,
    paddingVertical: 6,
  },
  tripFitLabelColumn: {
    flexShrink: 0,
    minWidth: 0,
    width: 140,
  },
  tripFitValueColumn: {
    flexShrink: 0,
    width: 140,
  },
  tripFitDetailColumn: {
    flex: 1.6,
  },
  tripFitDetailInput: {
    minHeight: 24,
    textAlignVertical: 'top',
  },
  inlineAddButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: designSystem.colors.lime,
    borderRadius: 14,
    flexDirection: 'row',
    gap: 5,
    marginTop: 6,
    minHeight: 26,
    paddingHorizontal: 9,
  },
  inlineAddText: {
    color: designSystem.colors.darkGreen,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
  },
  sectionBlock: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 8,
    paddingBottom: 10,
  },
  sectionBlockHeader: {
    gap: 3,
  },
  sectionBlockTitle: {
    color: designSystem.colors.ink,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  sectionBlockSubtitle: {
    color: designSystem.colors.mutedText,
    fontSize: 11,
    lineHeight: 16,
  },
  formGrid: {
    gap: 0,
  },
  availabilityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  availabilityCard: {
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 58,
    padding: 10,
  },
  availabilityLabel: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  availabilityOpen: {
    color: designSystem.colors.darkGreen,
  },
  availabilityFull: {
    color: designSystem.colors.copper,
  },
  availabilityMeta: {
    color: designSystem.colors.mutedText,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  managerField: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 5,
    minHeight: 42,
    paddingVertical: 7,
  },
  managerTextArea: {
    alignItems: 'flex-start',
    minHeight: 72,
  },
  fieldLabel: {
    color: designSystem.colors.subtleText,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 13,
    textTransform: 'uppercase',
    width: 160,
  },
  fieldValue: {
    color: designSystem.colors.ink,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  textInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    padding: 0,
  },
  textAreaInput: {
    minHeight: 54,
    textAlignVertical: 'top',
  },
  bulletList: {
    flex: 1,
    gap: 4,
  },
  listInput: {
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    fontSize: 13,
    lineHeight: 18,
    minHeight: 24,
    padding: 0,
  },
  optionTable: {
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  optionHeader: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  optionHeaderText: {
    color: designSystem.colors.subtleText,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  optionRow: {
    alignItems: 'flex-start',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    minHeight: 92,
    padding: 10,
  },
  compactOptionRow: {
    alignItems: 'center',
    minHeight: 46,
  },
  optionNameColumn: {
    flex: 1,
    minWidth: 0,
  },
  optionSmallColumn: {
    flexShrink: 0,
    width: 84,
  },
  optionActionColumn: {
    flexShrink: 0,
    width: 28,
  },
  optionInput: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    minHeight: 24,
    padding: 0,
  },
  compactStepperCell: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    justifyContent: 'flex-end',
  },
  compactStepperButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 10,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  compactStepperText: {
    color: designSystem.colors.darkGreen,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
  },
  compactStepperInput: {
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
    minWidth: 22,
    padding: 0,
    textAlign: 'center',
  },
  rowRemoveButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 13,
    flexShrink: 0,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  optionDetailInput: {
    fontWeight: '500',
    minHeight: 36,
    textAlignVertical: 'top',
  },
  optionMetaInput: {
    color: designSystem.colors.mutedText,
    fontSize: 11,
    lineHeight: 16,
    padding: 0,
  },
  bulletItem: {
    color: designSystem.colors.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  filterRow: {
    minHeight: 34,
  },
  bookingFilterContent: {
    paddingRight: 0,
  },
  bookingFilterTab: {
    minHeight: 32,
    minWidth: 96,
  },
  table: {
    borderRadius: 9,
    borderWidth: 1,
    overflow: 'hidden',
  },
  tableHeader: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  tableHeaderText: {
    color: designSystem.colors.subtleText,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  tableRow: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    minHeight: 66,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  guestColumn: {
    flex: 1,
    minWidth: 0,
  },
  bookingColumn: {
    flex: 1.45,
    minWidth: 0,
  },
  visitDetailColumn: {
    flex: 2.1,
    minWidth: 0,
  },
  statusColumn: {
    flexShrink: 0,
    width: 88,
  },
  actionColumn: {
    flexShrink: 0,
    width: 146,
  },
  identityCell: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  rowImage: {
    borderRadius: 8,
    height: 38,
    width: 38,
  },
  cellCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  rowTitle: {
    color: designSystem.colors.ink,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 17,
  },
  rowMeta: {
    color: designSystem.colors.mutedText,
    fontSize: 11,
    lineHeight: 16,
  },
  rowValue: {
    color: designSystem.colors.darkGreen,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
  },
  specialRequest: {
    color: designSystem.colors.copper,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
    textTransform: 'capitalize',
  },
  statusPending: {
    color: designSystem.colors.copper,
  },
  statusConfirmed: {
    color: designSystem.colors.darkGreen,
  },
  statusCancelled: {
    color: designSystem.colors.gray,
  },
  actionCell: {
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'flex-end',
  },
  actionButton: {
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 9,
  },
  actionButtonApprove: {
    backgroundColor: designSystem.colors.lime,
  },
  actionButtonCancel: {
    backgroundColor: designSystem.colors.scrimFaint,
  },
  actionButtonDisabled: {
    opacity: 0.55,
  },
  actionButtonText: {
    color: designSystem.colors.mutedText,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 13,
  },
  actionButtonTextApprove: {
    color: designSystem.colors.darkGreen,
  },
  noActionText: {
    color: designSystem.colors.gray,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
    textAlign: 'right',
  },
  ratingSummary: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 14,
  },
  ratingValue: {
    color: designSystem.colors.ink,
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 28,
  },
  ratingMeta: {
    color: designSystem.colors.mutedText,
    fontSize: 12,
    lineHeight: 16,
  },
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  galleryImage: {
    borderRadius: 9,
    height: 106,
    width: 136,
  },
  iconActions: {
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'flex-end',
  },
  iconAction: {
    alignItems: 'center',
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  dataRow: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 16,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  dataLabel: {
    color: designSystem.colors.subtleText,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
    textTransform: 'uppercase',
    width: 148,
  },
  dataValue: {
    color: designSystem.colors.ink,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  dataValueInput: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    minHeight: 22,
    padding: 0,
  },
  dataValueMultiline: {
    minHeight: 58,
    textAlignVertical: 'top',
  },
  selectCell: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  selectPill: {
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
  },
  selectPillActive: {
    backgroundColor: designSystem.colors.lime,
  },
  selectPillText: {
    color: designSystem.colors.mutedText,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
  },
  selectPillTextActive: {
    color: designSystem.colors.darkGreen,
  },
  mediaCell: {
    flex: 1,
    gap: 8,
  },
  mediaPreviewRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  schemaImagePreviewWrap: {
    position: 'relative',
  },
  schemaImagePreview: {
    borderRadius: 7,
    height: 48,
    width: 64,
  },
  removeImageButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.surface,
    borderRadius: 10,
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    right: -5,
    top: -5,
    width: 20,
  },
  cellActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  mediaLinkInput: {
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 8,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    minHeight: 28,
    minWidth: 220,
    paddingHorizontal: 9,
    paddingVertical: 0,
  },
  cellActionButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.lime,
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
  },
  cellActionText: {
    color: designSystem.colors.darkGreen,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
  },
  secondaryTinyButton: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrimFaint,
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 10,
  },
  secondaryTinyButtonText: {
    color: designSystem.colors.mutedText,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
  },
  coordinateCell: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  derivedLocationCell: {
    flex: 1,
    gap: 5,
  },
  derivedLocationTitle: {
    color: designSystem.colors.ink,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  derivedLocationMeta: {
    color: designSystem.colors.mutedText,
    fontSize: 12,
    lineHeight: 16,
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrim,
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  coordinateModal: {
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    maxWidth: 1120,
    padding: 16,
    width: '100%',
  },
  coordinateModalHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  coordinateSearchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  coordinatePickerLayout: {
    flexDirection: 'row',
    gap: 14,
    minHeight: 460,
  },
  coordinateSearchPane: {
    flexBasis: 360,
    flexGrow: 0,
    flexShrink: 0,
    gap: 10,
  },
  coordinateSearchInput: {
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    fontSize: 13,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  coordinateMapFrame: {
    borderRadius: 12,
    flex: 1,
    minHeight: 460,
    overflow: 'hidden',
  },
  coordinateMap: {
    flex: 1,
  },
  mapboxSuggestionList: {
    borderRadius: 10,
    flex: 1,
    overflow: 'hidden',
  },
  mapboxSuggestionRow: {
    backgroundColor: designSystem.colors.scrimFaint,
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  derivedLocationBox: {
    borderRadius: 10,
    borderWidth: 1,
    gap: 3,
    padding: 12,
  },
  emptyTableRow: {
    justifyContent: 'center',
    minHeight: 72,
    paddingHorizontal: 12,
  },
  emptyText: {
    color: designSystem.colors.mutedText,
    fontSize: 13,
    lineHeight: 18,
  },
  emptyDetail: {
    alignItems: 'center',
    flex: 1,
    gap: 10,
    justifyContent: 'center',
    padding: 24,
  },
  emptyIcon: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  emptyTitle: {
    color: designSystem.colors.ink,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  emptyBody: {
    color: designSystem.colors.mutedText,
    fontSize: 13,
    lineHeight: 18,
    maxWidth: 360,
    textAlign: 'center',
  },
  importReport: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 5,
    padding: 12,
  },
  createErrorReport: {
    backgroundColor: 'rgba(161, 75, 26, 0.14)',
  },
  importReportTitle: {
    color: designSystem.colors.ink,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 17,
  },
  importReportMessage: {
    color: designSystem.colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  promptModalBackdrop: {
    alignItems: 'center',
    backgroundColor: designSystem.colors.scrim,
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  promptModal: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 12,
    maxHeight: '86%',
    maxWidth: 920,
    padding: 16,
    width: '100%',
  },
  promptModalHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'space-between',
  },
  promptModalTitle: {
    color: designSystem.colors.ink,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
  },
  promptTextArea: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    minHeight: 260,
    padding: 12,
    textAlignVertical: 'top',
  },
  pasteCompilerBox: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 10,
    padding: 12,
  },
  pasteCompilerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  jsonEditorFrame: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    height: 320,
    overflow: 'hidden',
  },
  lineNumberGutter: {
    backgroundColor: designSystem.colors.scrimFaint,
    flexGrow: 0,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingTop: 11,
    width: 44,
  },
  lineNumberText: {
    color: designSystem.colors.gray,
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'right',
  },
  lineNumberTextError: {
    color: designSystem.colors.copper,
  },
  jsonEditorTextPane: {
    flex: 1,
    position: 'relative',
  },
  jsonHighlightLayer: {
    ...({ position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 }),
    overflow: 'hidden',
  },
  jsonHighlightContent: {
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  jsonSyntaxLine: {
    color: designSystem.colors.ink,
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    minHeight: 18,
  },
  jsonSyntaxKey: {
    color: designSystem.colors.darkGreen,
  },
  jsonSyntaxString: {
    color: designSystem.colors.copper,
  },
  jsonSyntaxNumber: {
    color: designSystem.colors.teal,
  },
  jsonSyntaxBoolean: {
    color: designSystem.colors.fern,
  },
  jsonSyntaxPunctuation: {
    color: designSystem.colors.gray,
  },
  jsonSyntaxPlain: {
    color: designSystem.colors.ink,
  },
  jsonEditorInput: {
    flex: 1,
    fontFamily: 'Courier',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    minHeight: 220,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  jsonEditorInputOverlay: {
    backgroundColor: 'transparent',
    height: '100%',
    position: 'absolute',
    width: '100%',
  },
  diagnosticsPanel: {
    gap: 6,
  },
  diagnosticRow: {
    alignItems: 'flex-start',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  diagnosticError: {
    backgroundColor: 'rgba(161, 75, 26, 0.14)',
  },
  diagnosticWarning: {
    backgroundColor: designSystem.colors.scrimFaint,
  },
  diagnosticInfo: {
    backgroundColor: designSystem.colors.limeSoft,
  },
  diagnosticLine: {
    color: designSystem.colors.gray,
    fontFamily: 'Courier',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
    width: 34,
  },
  diagnosticMessage: {
    color: designSystem.colors.ink,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  draftHeader: {
    alignItems: 'flex-start',
    borderBottomColor: designSystem.colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'space-between',
    padding: 16,
  },
  draftHeaderActions: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
  },
});

