import { Platform, StyleSheet } from 'react-native';

import { designSystem } from '@/constants/design-system';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  notice: {
    fontSize: 14,
    lineHeight: 20,
    color: designSystem.colors.copper,
  },
  sheetContent: {
    paddingTop: designSystem.spacing.lg,
    paddingHorizontal: designSystem.spacing.lg,
    gap: 18,
  },
  scheduleSheetContent: {
    paddingTop: designSystem.spacing.lg,
    paddingHorizontal: designSystem.spacing.lg,
    gap: 26,
  },
  scheduleHeader: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  scheduleHeaderAction: {
    minWidth: 78,
    minHeight: 44,
    justifyContent: 'center',
  },
  scheduleHeaderActionText: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '500',
    color: designSystem.colors.ink,
  },
  scheduleHeaderActionDisabled: {
    opacity: 0.45,
  },
  scheduleHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 21,
    lineHeight: 25,
    fontWeight: '600',
    color: designSystem.colors.ink,
  },
  scheduleTextCard: {
    minHeight: 210,
    borderRadius: 22,
    backgroundColor: Platform.OS === 'android' ? designSystem.colors.surfaceRaised : designSystem.colors.whiteGlassStrong,
    borderWidth: 1,
    borderColor: Platform.OS === 'android' ? designSystem.colors.lightSurfaceAlt : designSystem.colors.borderSoft,
    overflow: 'hidden',
  },
  scheduleTitleInput: {
    minHeight: 70,
    paddingHorizontal: 18,
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '500',
    color: designSystem.colors.ink,
  },
  scheduleDescriptionInput: {
    minHeight: 118,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 24,
    textAlignVertical: 'top',
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '500',
    color: designSystem.colors.ink,
  },
  descriptionLimitText: {
    position: 'absolute',
    right: 18,
    bottom: 14,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '600',
    color: designSystem.colors.gray,
  },
  scheduleDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: designSystem.colors.borderSoft,
    marginLeft: 18,
  },
  scheduleDateCard: {
    borderRadius: 22,
    backgroundColor: Platform.OS === 'android' ? designSystem.colors.surfaceRaised : designSystem.colors.whiteGlassStrong,
    borderWidth: 1,
    borderColor: Platform.OS === 'android' ? designSystem.colors.lightSurfaceAlt : designSystem.colors.borderSoft,
    overflow: 'hidden',
  },
  scheduleDateRow: {
    minHeight: 74,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  scheduleDateRowDisabled: {
    opacity: 0.45,
  },
  scheduleCardLabel: {
    minWidth: 92,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '500',
    color: designSystem.colors.ink,
  },
  scheduleDateControls: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  scheduleDatePills: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  scheduleDatePill: {
    maxWidth: 132,
    overflow: 'hidden',
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '600',
    color: designSystem.colors.ink,
    backgroundColor: Platform.OS === 'android' ? designSystem.colors.surface : designSystem.colors.whiteOverlayFaint,
  },
  includeEndRow: {
    minHeight: 70,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  scheduleHelpText: {
    marginTop: -18,
    paddingHorizontal: 18,
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '500',
    color: designSystem.colors.gray,
  },
  scheduleOptionRow: {
    minHeight: 74,
    borderRadius: 22,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    backgroundColor: Platform.OS === 'android' ? designSystem.colors.surfaceRaised : designSystem.colors.whiteGlassStrong,
    borderWidth: 1,
    borderColor: Platform.OS === 'android' ? designSystem.colors.lightSurfaceAlt : designSystem.colors.borderSoft,
  },
  scheduleOptionLabel: {
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '500',
    color: designSystem.colors.ink,
  },
  scheduleOptionValueWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  scheduleOptionValue: {
    flexShrink: 1,
    textAlign: 'right',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '600',
    color: designSystem.colors.gray,
  },
  scheduleAdjustRow: {
    flexDirection: 'row',
    gap: 8,
  },
  smallIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: designSystem.colors.limeSoft,
    borderWidth: 1,
    borderColor: designSystem.colors.borderSoft,
  },
});
