export const demoExploreTravelers = [
  { slug: 'local-demo-traveler', name: 'Lea', countryCode: 'DE', countryLabel: 'Germany', phoneNumber: '+4915200000001' },
  { slug: 'anna-berlin', name: 'Anna', countryCode: 'DE', countryLabel: 'Germany', phoneNumber: '+4915200000002' },
  { slug: 'jonas-hamburg', name: 'Jonas', countryCode: 'DE', countryLabel: 'Germany', phoneNumber: '+4915200000003' },
  { slug: 'mia-munich', name: 'Mia', countryCode: 'DE', countryLabel: 'Germany', phoneNumber: '+4915200000004' },
  { slug: 'liam-cape-town', name: 'Liam', countryCode: 'ZA', countryLabel: 'South Africa', phoneNumber: '+27820000001' },
  { slug: 'ava-joburg', name: 'Ava', countryCode: 'ZA', countryLabel: 'South Africa', phoneNumber: '+27820000002' },
  { slug: 'noah-london', name: 'Noah', countryCode: 'GB', countryLabel: 'United Kingdom', phoneNumber: '+447700900001' },
  { slug: 'zoe-paris', name: 'Zoe', countryCode: 'FR', countryLabel: 'France', phoneNumber: '+33610000001' },
  { slug: 'luc-amsterdam', name: 'Luc', countryCode: 'NL', countryLabel: 'Netherlands', phoneNumber: '+31610000001' },
  { slug: 'maya-new-york', name: 'Maya', countryCode: 'US', countryLabel: 'United States', phoneNumber: '+12125550001' },
  { slug: 'elias-windhoek', name: 'Elias', countryCode: 'NA', countryLabel: 'Namibia', phoneNumber: '+264810000001' },
  { slug: 'luca-zurich', name: 'Luca', countryCode: 'CH', countryLabel: 'Switzerland', phoneNumber: '+41790000001' },
  { slug: 'sofia-lisbon', name: 'Sofia', countryCode: 'PT', countryLabel: 'Portugal', phoneNumber: '+351910000001' },
  { slug: 'max-vienna', name: 'Max', countryCode: 'AT', countryLabel: 'Austria', phoneNumber: '+436601000001' },
  { slug: 'chloe-melbourne', name: 'Chloe', countryCode: 'AU', countryLabel: 'Australia', phoneNumber: '+61415000001' },
  { slug: 'james-toronto', name: 'James', countryCode: 'CA', countryLabel: 'Canada', phoneNumber: '+14165550001' },
] as const;
