
export const demoExploreBookings = [
  { experienceSlug: 'windhoek-craft-market-walk', travelerSlug: 'local-demo-traveler' },
  { experienceSlug: 'naankuse-wildlife-encounter', travelerSlug: 'local-demo-traveler' },
  { experienceSlug: 'taste-of-swakop', travelerSlug: 'local-demo-traveler' },
  { experienceSlug: 'quad-sandboard', travelerSlug: 'local-demo-traveler' },
  { experienceSlug: 'desert-adrenaline', travelerSlug: 'local-demo-traveler' },

  { experienceSlug: 'windhoek-craft-market-walk', travelerSlug: 'elias-windhoek' },
  { experienceSlug: 'windhoek-craft-market-walk', travelerSlug: 'noah-london' },
  { experienceSlug: 'naankuse-wildlife-encounter', travelerSlug: 'liam-cape-town' },
  { experienceSlug: 'naankuse-wildlife-encounter', travelerSlug: 'ava-joburg' },
  { experienceSlug: 'desert-adrenaline', travelerSlug: 'anna-berlin' },
  { experienceSlug: 'desert-adrenaline', travelerSlug: 'jonas-hamburg' },
  { experienceSlug: 'desert-adrenaline', travelerSlug: 'mia-munich' },
  { experienceSlug: 'quad-sandboard', travelerSlug: 'liam-cape-town' },
  { experienceSlug: 'quad-sandboard', travelerSlug: 'ava-joburg' },
  { experienceSlug: 'taste-of-swakop', travelerSlug: 'noah-london' },
  { experienceSlug: 'walvis-lagoon-kayak', travelerSlug: 'zoe-paris' },
  { experienceSlug: 'spitzkoppe-stargazing-camp', travelerSlug: 'luc-amsterdam' },
  { experienceSlug: 'etosha-game-drive', travelerSlug: 'maya-new-york' },
  { experienceSlug: 'sossusvlei-sunrise-drive', travelerSlug: 'anna-berlin' },
  { experienceSlug: 'sossusvlei-sunrise-drive', travelerSlug: 'jonas-hamburg' },
  { experienceSlug: 'fish-river-canyon-rim-hike', travelerSlug: 'luca-zurich' },
  { experienceSlug: 'zambezi-houseboat-safari', travelerSlug: 'noah-london' },
  { experienceSlug: 'kolmanskop-ghost-town', travelerSlug: 'anna-berlin' },
  { experienceSlug: 'kolmanskop-ghost-town', travelerSlug: 'sofia-lisbon' },
  { experienceSlug: 'twyfelfontein-rock-art', travelerSlug: 'max-vienna' },
  { experienceSlug: 'twyfelfontein-rock-art', travelerSlug: 'luc-amsterdam' },
  { experienceSlug: 'brandberg-white-lady-hike', travelerSlug: 'chloe-melbourne' },
  { experienceSlug: 'cape-cross-seal-reserve', travelerSlug: 'liam-cape-town' },
  { experienceSlug: 'sandwich-harbour-4x4', travelerSlug: 'anna-berlin' },
  { experienceSlug: 'sandwich-harbour-4x4', travelerSlug: 'mia-munich' },
  { experienceSlug: 'cheetah-conservation-fund', travelerSlug: 'maya-new-york' },
  { experienceSlug: 'cheetah-conservation-fund', travelerSlug: 'james-toronto' },
  { experienceSlug: 'namibrand-dark-sky-reserve', travelerSlug: 'luca-zurich' },
  { experienceSlug: 'namibrand-dark-sky-reserve', travelerSlug: 'sofia-lisbon' },
  { experienceSlug: 'hoba-meteorite-grootfontein', travelerSlug: 'max-vienna' },
  { experienceSlug: 'quiver-tree-forest-keetmanshoop', travelerSlug: 'ava-joburg' },
  { experienceSlug: 'ai-ais-hot-springs', travelerSlug: 'noah-london' },
  { experienceSlug: 'popa-falls-divundu', travelerSlug: 'liam-cape-town' },
  { experienceSlug: 'waterberg-plateau-hike', travelerSlug: 'mia-munich' },
  { experienceSlug: 'duwisib-castle', travelerSlug: 'jonas-hamburg' },
  { experienceSlug: 'epupa-falls-kaokoveld', travelerSlug: 'chloe-melbourne' },
] as const;
