import {
  WINDHOEK_IMAGE,
  NAANKUSE_IMAGE,
  SKYDIVE_IMAGE,
  SANDBOARD_IMAGE,
  SWAKOP_FOOD_IMAGE,
  DESERT_4X4_IMAGE,
  LAGOON_KAYAK_IMAGE,
  SANDWICH_HARBOUR_IMAGE,
  CAPE_CROSS_IMAGE,
  TWYFELFONTEIN_IMAGE,
  BRANDBERG_IMAGE,
  PETRIFIED_FOREST_IMAGE,
  VINGERKLIP_IMAGE,
  EPUPA_FALLS_IMAGE,
  SPITZKOPPE_IMAGE,
  WATERBERG_IMAGE,
  CHEETAH_IMAGE,
  HOBA_IMAGE,
  ETOSHA_IMAGE,
  SOSSUSVLEI_IMAGE,
  DEADVLEI_IMAGE,
  NAMIBRAND_IMAGE,
  KOLMANSKOP_IMAGE,
  QUIVER_TREE_IMAGE,
  FISH_CANYON_IMAGE,
  AI_AIS_IMAGE,
  DUWISIB_IMAGE,
  POPA_FALLS_IMAGE,
  ZAMBEZI_IMAGE,
  SALT_PANS_IMAGE,
} from './constants';

export const seedExperiences = [
      // ── WINDHOEK AREA ─────────────────────────────────────────────────────
      {
        slug: 'windhoek-craft-market-walk',
        badge: 'City Starter',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Windhoek Craft Walk',
        subtitle: 'Old Brewery, local design studios, and coffee stops',
        description:
          'A city-first route that begins in Windhoek with contemporary Namibian design, easy food stops, and enough structure to feel curated without losing the looseness of a first day.',
        imageUri: WINDHOEK_IMAGE,
        price: 'N$650',
        priceSuffix: 'Per person',
        category: 'Culture',
        coordinate: [17.0832, -22.5700],
        geography: { region: 'Khomas', town: 'Windhoek' },
        locationLabel: 'Windhoek West',
        durationLabel: '3 hours',
        groupSizeLabel: 'Up to 10 guests',
        tripFit: [
          { label: 'Category', value: 'CULTURE', detail: 'A stronger fit for travelers who want the capital to feel like part of the trip, not just transit.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '3 HOURS', detail: 'Easy on arrival day or before heading out on a longer road route.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 10', detail: 'Flexible for solo travelers, pairs, or a small group starting together.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [WINDHOEK_IMAGE, NAANKUSE_IMAGE],
        travelerMomentum: { countryCode: 'NA', countryLabel: 'Namibia', visitorCount: 8, summary: '8 local and regional travelers used this as their Windhoek starting point.' },
        booking: { availabilityLabel: 'Morning and afternoon departures', confirmMode: 'Host confirmation within 2 hours', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Local guide', 'Coffee stop', 'Craft market entry', 'Flexible finish near restaurants or galleries'],
      },
      {
        slug: 'naankuse-wildlife-encounter',
        badge: 'Wildlife',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Naankuse Wildlife Encounter',
        subtitle: 'Conservation drive and rescue center visit outside Windhoek',
        description:
          'Head just outside the capital for a conservation-focused wildlife outing with rescue stories, responsible viewing, and a lighter logistics load than a full safari transfer.',
        imageUri: NAANKUSE_IMAGE,
        price: 'N$1,450',
        priceSuffix: 'Per person',
        category: 'Wildlife',
        coordinate: [17.2090, -22.4390],
        geography: { region: 'Khomas', town: 'Windhoek' },
        locationLabel: 'Naankuse Reserve, 25 km from Windhoek',
        durationLabel: 'Half day',
        groupSizeLabel: 'Small group',
        tripFit: [
          { label: 'Category', value: 'WILDLIFE', detail: 'A good first wildlife day when you are still based near Windhoek.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'HALF DAY', detail: 'Feels substantial without consuming the whole travel day.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'SMALL GROUP', detail: 'Keeps the guide contact personal and the pace steady.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [NAANKUSE_IMAGE, WINDHOEK_IMAGE],
        travelerMomentum: { countryCode: 'ZA', countryLabel: 'South Africa', visitorCount: 6, summary: '6 travelers from South Africa booked this as a quick wildlife add-on near Windhoek.' },
        booking: { availabilityLabel: 'Next departure: Tomorrow at 08:00', confirmMode: 'Instant confirmation', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Reserve transfer from Windhoek', 'Guide-led conservation drive', 'Rescue center access', 'Refreshment stop'],
      },
      // ── SWAKOPMUND ────────────────────────────────────────────────────────
      {
        slug: 'tandem-skydive',
        badge: 'Top Rated',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Tandem Skydive',
        subtitle: 'Freefall over the Namib Desert at 10,000 ft',
        description:
          'Jump into a guided tandem skydive with wide-open views of the dunes, the Atlantic edge, and the full Swakopmund coastline before landing back near the desert strip.',
        imageUri: SKYDIVE_IMAGE,
        price: 'EUR 180',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [14.5684, -22.6621],
        geography: { region: 'Erongo', town: 'Swakopmund' },
        locationLabel: 'Swakopmund Airfield',
        durationLabel: '3 hours',
        groupSizeLabel: '2 people per jump',
        tripFit: [
          { label: 'Category', value: 'ADVENTURE', detail: 'Built for travelers chasing one headline moment in the desert.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '3 HOURS', detail: 'Easy to slot into a half-day plan without losing the rest of the trip.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: '2 PER JUMP', detail: 'Best when you want a tight tandem setup and fast movement on the ground.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [SKYDIVE_IMAGE, DESERT_4X4_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 42, summary: '42 travelers from Germany booked this drop zone recently.' },
        booking: { availabilityLabel: 'Next opening: Tomorrow at 09:00', confirmMode: 'Instant confirmation', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Hotel pickup on request', 'Tandem instructor and safety gear', 'Pre-jump briefing', 'Landing transfer back to town'],
      },
      {
        slug: 'quad-sandboard',
        badge: 'Best Value',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Quad + Sandboard',
        subtitle: '4-hour desert adventure in the Namib dune belt',
        description:
          'Ride deep into the dunes by quad bike, stop for guided sandboarding runs, and settle into a slower scenic return with enough time to pair this with the rest of the day.',
        imageUri: SANDBOARD_IMAGE,
        price: 'EUR 65',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [14.5430, -22.6670],
        geography: { region: 'Erongo', town: 'Swakopmund' },
        locationLabel: 'Dune belt outside Swakopmund',
        durationLabel: '4 hours',
        groupSizeLabel: 'Up to 8 riders',
        tripFit: [
          { label: 'Category', value: 'ADVENTURE', detail: 'A more social desert session with motion from start to finish.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '4 HOURS', detail: 'Long enough to feel like a proper outing, short enough for a flexible day.', icon: 'clock', tone: 'light' },
          { label: 'Group Size', value: 'UP TO 8', detail: 'Works well for friends or mixed groups who want one shared booking.', icon: 'users', tone: 'accent' },
        ],
        galleryImages: [SANDBOARD_IMAGE, DESERT_4X4_IMAGE],
        travelerMomentum: { countryCode: 'ZA', countryLabel: 'South Africa', visitorCount: 19, summary: '19 travelers from South Africa added this ride to their desert day.' },
        booking: { availabilityLabel: 'Open this afternoon', confirmMode: 'Guide approval within 1 hour', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Guide-led desert route', 'Quad and sandboard rental', 'Protective gear', 'Water and cool-down stop'],
      },
      {
        slug: 'desert-adrenaline',
        badge: 'Adrenaline',
        ctaLabel: 'Reserve experience',
        title: 'Desert Adrenaline',
        subtitle: '4x4 dunes and high-speed sandboarding',
        description:
          'A fast, visual desert session built around dune driving, short adrenaline bursts, and enough flexibility to drop neatly into a trip day without turning into an editorial detour.',
        imageUri: DESERT_4X4_IMAGE,
        price: 'N$1,850',
        priceSuffix: 'Per rider',
        category: 'Adventure',
        coordinate: [14.5380, -22.6890],
        geography: { region: 'Erongo', town: 'Swakopmund' },
        locationLabel: 'Namib dune corridor, south of Swakopmund',
        durationLabel: 'Half day',
        groupSizeLabel: 'Small group',
        tripFit: [
          { label: 'Category', value: 'ADRENALINE', detail: 'For travelers who want speed, dunes, and a more cinematic route.', icon: 'compass', tone: 'accent' },
          { label: 'Duration', value: 'HALF DAY', detail: 'A bigger outing that still leaves room for a slower evening booking.', icon: 'clock', tone: 'dark' },
          { label: 'Group Size', value: 'SMALL GROUP', detail: 'Keeps the pace fast without turning the trip into a crowd experience.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [DESERT_4X4_IMAGE, SANDBOARD_IMAGE, SKYDIVE_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 42, summary: '42 travelers from Germany are visiting this week.' },
        booking: { availabilityLabel: 'Next opening: Sunset slot', confirmMode: 'Instant confirmation', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['4x4 dune transfer', 'Sandboard gear', 'Guide and safety briefing', 'Sunset ridge stop'],
      },
      {
        slug: 'taste-of-swakop',
        badge: 'Gastronomy',
        ctaLabel: 'Reserve table',
        title: 'Taste of Swakop',
        subtitle: 'Atlantic oysters and local craft brews at the Jetty',
        description:
          'A slower booking anchored around seafood, local pours, and the Jetty edge of town, ideal when the traveler wants one concrete reservation instead of a story-led browse.',
        imageUri: SWAKOP_FOOD_IMAGE,
        price: 'USD 45',
        priceSuffix: '/pp',
        category: 'Gastronomy',
        coordinate: [14.5040, -22.6780],
        geography: { region: 'Erongo', town: 'Swakopmund' },
        locationLabel: 'Swakopmund Jetty (built 1912)',
        durationLabel: '2 hours',
        groupSizeLabel: 'Tables from 2 to 6',
        tripFit: [
          { label: 'Category', value: 'DINING', detail: 'A calmer reservation for travelers who want one solid evening anchor.', icon: 'compass', tone: 'light' },
          { label: 'Duration', value: '2 HOURS', detail: 'Easy to layer after a beach day or before a quieter night in town.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: '2 TO 6', detail: 'Flexible for couples, small friend groups, or an easy celebration meal.', icon: 'users', tone: 'dark' },
        ],
        galleryImages: [SWAKOP_FOOD_IMAGE, LAGOON_KAYAK_IMAGE],
        travelerMomentum: { countryCode: 'GB', countryLabel: 'United Kingdom', visitorCount: 11, summary: '11 travelers from the United Kingdom reserved tables near the Jetty.' },
        booking: { availabilityLabel: 'Dinner tables open tonight', confirmMode: 'Restaurant confirmation', addToTripLabel: 'Add dinner to trip', continueWithoutTripLabel: 'Reserve without trip' },
        includes: ['Reserved table', 'Oyster tasting flight', 'Craft pairing option', 'Jetty-side seating request'],
      },
      // ── WALVIS BAY ────────────────────────────────────────────────────────
      {
        slug: 'walvis-lagoon-kayak',
        badge: 'Coastal',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Walvis Lagoon Kayak',
        subtitle: 'Pelican Point paddle with seals and calm water channels',
        description:
          'A low-impact marine outing that swaps high-adrenaline dune energy for lagoon wildlife, long horizons, and a steady paddle pace out of Walvis Bay.',
        imageUri: LAGOON_KAYAK_IMAGE,
        price: 'N$1,150',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [14.5036, -22.9576],
        geography: { region: 'Erongo', town: 'Walvis Bay' },
        locationLabel: 'Walvis Bay Lagoon — Ramsar Wetland Site',
        durationLabel: '3 hours',
        groupSizeLabel: 'Up to 12 paddlers',
        tripFit: [
          { label: 'Category', value: 'COASTAL', detail: 'A calmer active option for travelers who still want real movement and scenery.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '3 HOURS', detail: 'Easy to pair with lunch or a scenic drive up the coast afterward.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 12', detail: 'Works especially well for friend groups and mixed-skill paddlers.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [LAGOON_KAYAK_IMAGE, SWAKOP_FOOD_IMAGE],
        travelerMomentum: { countryCode: 'FR', countryLabel: 'France', visitorCount: 7, summary: '7 travelers from France booked this lagoon outing recently.' },
        booking: { availabilityLabel: 'Morning paddle slots open', confirmMode: 'Instant confirmation', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Kayak and paddle', 'Marine guide', 'Dry bag', 'Hot drink after the paddle'],
      },
      {
        slug: 'sandwich-harbour-4x4',
        badge: 'Remote Coast',
        badgeTone: 'dark',
        ctaLabel: 'Reserve experience',
        title: 'Sandwich Harbour 4x4',
        subtitle: 'Dunes crashing into the Atlantic — tidal beach driving and vast star dune scenery',
        description:
          'One of the most dramatic coastal landscapes in the world — towering Namib star dunes descending directly into the South Atlantic surf. Reachable only by 4x4 through a tidal beach corridor.',
        imageUri: SANDWICH_HARBOUR_IMAGE,
        price: 'N$1,650',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [14.4083, -23.3917],
        geography: { region: 'Erongo', town: 'Walvis Bay' },
        locationLabel: '50 km south of Walvis Bay via tidal beach',
        durationLabel: 'Half day',
        groupSizeLabel: 'Up to 8 per vehicle',
        tripFit: [
          { label: 'Category', value: 'REMOTE COAST', detail: 'For travelers chasing one of southern Africa\'s most dramatic and least-visited landscapes.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'HALF DAY', detail: 'Tidal windows dictate scheduling — typically morning departures from Walvis Bay.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 8', detail: 'Vehicle-based experience — small group size keeps the atmosphere close.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [SANDWICH_HARBOUR_IMAGE, SALT_PANS_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 14, summary: '14 travelers from Germany rated this their most memorable Namibia landscape.' },
        booking: { availabilityLabel: 'Morning departures — tide-dependent', confirmMode: 'Guide confirmation within 2 hours', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['4x4 vehicle and experienced guide', 'Beach driving along the tidal corridor', 'Dune stop with panoramic view', 'Flamingo lagoon pass on return'],
      },
      // ── SKELETON COAST ────────────────────────────────────────────────────
      {
        slug: 'cape-cross-seal-reserve',
        badge: 'Wildlife Mass',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Cape Cross Seal Reserve',
        subtitle: 'One of the largest Cape fur seal colonies on Earth on the Skeleton Coast',
        description:
          'A raw, overwhelming wildlife experience at one of Africa\'s largest seal colonies — estimated at over 100,000 animals at peak season, with jackals and brown hyenas patrolling the edge.',
        imageUri: CAPE_CROSS_IMAGE,
        price: 'N$80',
        priceSuffix: 'Entry per person',
        category: 'Wildlife',
        coordinate: [13.9500, -21.7667],
        geography: { region: 'Erongo', town: 'Henties Bay' },
        locationLabel: 'Cape Cross, 120 km north of Swakopmund on the C34',
        durationLabel: '2 hours',
        groupSizeLabel: 'Self-drive or guided',
        tripFit: [
          { label: 'Category', value: 'RAW WILDLIFE', detail: 'For travelers who want unscripted, overwhelming scale — not a curated encounter.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '2 HOURS', detail: 'Enough time to walk the boardwalk and absorb the sheer scale of the colony.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY SIZE', detail: 'Open access — no group limit, though crowds are rare on weekdays.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [CAPE_CROSS_IMAGE, SALT_PANS_IMAGE],
        travelerMomentum: { countryCode: 'ZA', countryLabel: 'South Africa', visitorCount: 22, summary: '22 travelers from South Africa listed this as their most visceral Namibia stop.' },
        booking: { availabilityLabel: 'Open daily from 08:00', confirmMode: 'Self-entry at the gate', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Park entry', 'Accessible boardwalk along the colony', 'Wildlife guide available on request', 'Scenic Skeleton Coast drive context'],
      },
      // ── DAMARALAND ────────────────────────────────────────────────────────
      {
        slug: 'twyfelfontein-rock-art',
        badge: 'UNESCO',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Twyfelfontein Rock Art',
        subtitle: 'Over 2,000 ancient San engravings — Namibia\'s first UNESCO World Heritage Site',
        description:
          'One of Africa\'s most significant concentrations of ancient rock art — San shamans carved these images into red Etjo sandstone up to 6,000 years ago in the open landscape of Damaraland.',
        imageUri: TWYFELFONTEIN_IMAGE,
        price: 'N$950',
        priceSuffix: 'Per person',
        category: 'Culture',
        coordinate: [14.3667, -20.5833],
        geography: { region: 'Kunene', town: 'Khorixas area' },
        locationLabel: 'Twyfelfontein, Damaraland — 110 km from Khorixas',
        durationLabel: '2–3 hours',
        groupSizeLabel: 'Up to 12 per guide group',
        tripFit: [
          { label: 'Category', value: 'CULTURE', detail: 'For travelers who want landscape and deep history woven together.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '2–3 HOURS', detail: 'Worth spending full time with a guide who can explain the iconography and context.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 12', detail: 'Guided entry protects the engravings and gives depth to the visit.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [TWYFELFONTEIN_IMAGE, PETRIFIED_FOREST_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 18, summary: '18 travelers from Germany visited as part of their Damaraland self-drive loop.' },
        booking: { availabilityLabel: 'Morning and afternoon tours daily', confirmMode: 'Booked at the site entrance', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Licensed site guide (mandatory)', 'Access to multiple engraving panels', 'Organ Pipes viewpoint included', 'Burnt Mountain stop on departure'],
      },
      {
        slug: 'brandberg-white-lady-hike',
        badge: 'Cultural Trek',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Brandberg White Lady Hike',
        subtitle: '4 km gorge hike to ancient San rock paintings in Namibia\'s highest mountain',
        description:
          'A proper hike through the Tsisab Gorge at the base of the Brandberg Massif — Namibia\'s highest peak at 2,573 m — to see the famous White Lady rock painting dated to over 2,000 years old.',
        imageUri: BRANDBERG_IMAGE,
        price: 'N$850',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [14.6833, -21.1167],
        geography: { region: 'Erongo', town: 'Uis' },
        locationLabel: 'Brandberg Massif, Tsisab Gorge — 30 km from Uis',
        durationLabel: '3 hours',
        groupSizeLabel: 'Up to 10 per guide',
        tripFit: [
          { label: 'Category', value: 'HIKE + CULTURE', detail: 'For active travelers who want genuine effort and cultural discovery combined.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '3 HOURS', detail: 'Best started before 08:00 to complete before the gorge heats significantly.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 10', detail: 'Guide is mandatory — keeps the group focused and the site protected.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [BRANDBERG_IMAGE, TWYFELFONTEIN_IMAGE],
        travelerMomentum: { countryCode: 'NL', countryLabel: 'Netherlands', visitorCount: 9, summary: '9 travelers from the Netherlands ranked this their top Namibia active day.' },
        booking: { availabilityLabel: 'Best timing: 07:00 departure', confirmMode: 'Guide arranged at Brandberg White Lady Lodge', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Licensed site guide (mandatory)', 'Gorge route navigation', 'Rock art interpretation', 'Water resupply at trailhead'],
      },
      // ── SPITZKOPPE ────────────────────────────────────────────────────────
      {
        slug: 'spitzkoppe-stargazing-camp',
        badge: 'Night Sky',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Spitzkoppe Stargazing Camp',
        subtitle: 'Granite peaks, campfire dinner, and desert night sky viewing',
        description:
          'Trade the coast for granite domes and a big-sky desert night with guided stargazing, simple camp comforts, and a landscape that feels completely stripped back.',
        imageUri: SPITZKOPPE_IMAGE,
        price: 'N$2,600',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [15.1985, -21.8216],
        geography: { region: 'Erongo', town: 'Spitzkoppe' },
        locationLabel: 'Spitzkoppe Massif — 200 km north of Swakopmund',
        durationLabel: 'Overnight',
        groupSizeLabel: 'Small camp group',
        tripFit: [
          { label: 'Category', value: 'STARGAZING', detail: 'Best for travelers who want atmosphere, geology, and one memorable night outside town.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'OVERNIGHT', detail: 'Needs a deliberate slot in the route, but pays off with a completely different rhythm.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'SMALL CAMP', detail: 'Keeps the experience intimate and quiet once the sun drops.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [SPITZKOPPE_IMAGE, NAMIBRAND_IMAGE],
        travelerMomentum: { countryCode: 'NL', countryLabel: 'Netherlands', visitorCount: 5, summary: '5 travelers from the Netherlands saved this for their central Namibia route.' },
        booking: { availabilityLabel: 'Next camp: Friday night', confirmMode: 'Host confirmation within 4 hours', addToTripLabel: 'Add overnight to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Camp setup', 'Guide-led stargazing', 'Dinner by the fire', 'Sunrise coffee'],
      },
      // ── ETOSHA ────────────────────────────────────────────────────────────
      {
        slug: 'etosha-game-drive',
        badge: 'Safari',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Etosha Game Drive',
        subtitle: 'Full-day waterhole route through Etosha National Park',
        description:
          'A full safari day built around waterhole timing, long wildlife windows, and a route that gives travelers a real shot at Etosha — elephant, lion, black rhino, and vast herds — without forcing a luxury-lodge framing.',
        imageUri: ETOSHA_IMAGE,
        price: 'N$3,400',
        priceSuffix: 'Per person',
        category: 'Wildlife',
        coordinate: [15.9113, -19.1780],
        geography: { region: 'Oshikoto', town: 'Etosha' },
        locationLabel: 'Okaukuejo waterhole, Etosha National Park',
        durationLabel: 'Full day',
        groupSizeLabel: '6 guests max',
        tripFit: [
          { label: 'Category', value: 'SAFARI', detail: 'A major wildlife day for travelers who want classic Namibia animal sightings.', icon: 'compass', tone: 'accent' },
          { label: 'Duration', value: 'FULL DAY', detail: 'A committed outing that works best when the itinerary leaves room for one headline safari block.', icon: 'clock', tone: 'dark' },
          { label: 'Group Size', value: '6 MAX', detail: 'Small enough for guide commentary and frequent viewing stops.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [ETOSHA_IMAGE, CHEETAH_IMAGE],
        travelerMomentum: { countryCode: 'US', countryLabel: 'United States', visitorCount: 9, summary: '9 travelers from the United States picked this as their Namibia safari day.' },
        booking: { availabilityLabel: 'Best next slot: Sunrise departure', confirmMode: 'Instant confirmation', addToTripLabel: 'Add safari to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Park transfer from Andersson Gate', 'Guide and game vehicle', 'Park entry coordination', 'Cooler with drinks and snacks'],
      },
      // ── SOSSUSVLEI / NAMIB ────────────────────────────────────────────────
      {
        slug: 'sossusvlei-sunrise-drive',
        badge: 'Desert Icon',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Sossusvlei Sunrise Drive',
        subtitle: 'Sunrise dunes, Deadvlei walk, and Sesriem Canyon stop',
        description:
          'A big-desert day anchored around the light at Sossusvlei and Deadvlei, designed for travelers who want one iconic Namibia outing and are happy to commit to the road time it deserves.',
        imageUri: SOSSUSVLEI_IMAGE,
        price: 'N$4,200',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [15.3449, -24.7339],
        geography: { region: 'Hardap', town: 'Sesriem' },
        locationLabel: 'Sesriem Gate, Namib-Naukluft National Park',
        durationLabel: 'Full day',
        groupSizeLabel: '4x4 small group',
        tripFit: [
          { label: 'Category', value: 'DESERT', detail: 'The strongest fit for travelers chasing one unmistakable Namibia landscape.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'FULL DAY', detail: 'A full commitment, but the visual payoff makes it one of the country-defining outings.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'SMALL 4X4', detail: 'Keeps the transfers focused and the dune timing more efficient.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [SOSSUSVLEI_IMAGE, DEADVLEI_IMAGE, NAMIBRAND_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 12, summary: '12 travelers from Germany booked this iconic desert day.' },
        booking: { availabilityLabel: 'Next run: 05:00 departure from Sesriem', confirmMode: 'Guide confirmation within 2 hours', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['4x4 transfer inside the park', 'Guide-led dune timing (Big Daddy or Dune 45)', 'Deadvlei clay pan walk', 'Sesriem Canyon stop on return'],
      },
      {
        slug: 'namibrand-dark-sky-reserve',
        badge: 'Dark Sky',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'NamibRand Dark Sky Reserve',
        subtitle: 'Africa\'s first International Dark Sky Reserve — guided Milky Way sessions on a private reserve',
        description:
          'Trade town lights for absolute darkness on 172,200 hectares of private reserve bordering the Namib-Naukluft National Park. One of the best Milky Way viewing sites in the southern hemisphere.',
        imageUri: NAMIBRAND_IMAGE,
        price: 'N$1,800',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [16.1000, -25.0500],
        geography: { region: 'Hardap', town: 'Sesriem area' },
        locationLabel: 'NamibRand Nature Reserve, east of Sossusvlei',
        durationLabel: 'Overnight',
        groupSizeLabel: 'Small group',
        tripFit: [
          { label: 'Category', value: 'STARGAZING', detail: 'For travelers who want the definitive southern hemisphere dark-sky experience.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'OVERNIGHT', detail: 'The sky builds for hours after dark — staying overnight unlocks the full experience.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'SMALL GROUP', detail: 'Intimate guide groups maximise telescope time and narrative quality.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [NAMIBRAND_IMAGE, SOSSUSVLEI_IMAGE],
        travelerMomentum: { countryCode: 'US', countryLabel: 'United States', visitorCount: 7, summary: '7 travelers from the United States rated this their single best Namibia night.' },
        booking: { availabilityLabel: 'New moon dates book fast — plan ahead', confirmMode: 'Lodge confirmation within 6 hours', addToTripLabel: 'Add overnight to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Guided telescope session', 'Dark-sky reserve certification briefing', 'Dinner and overnight accommodation', 'Sunrise desert walk'],
      },
      // ── SOUTHERN NAMIBIA ──────────────────────────────────────────────────
      {
        slug: 'kolmanskop-ghost-town',
        badge: 'Ghost Town',
        badgeTone: 'dark',
        ctaLabel: 'Reserve experience',
        title: 'Kolmanskop Ghost Town',
        subtitle: 'Diamond-era mansions buried in Namib sand — 10 km from Lüderitz',
        description:
          'One of Africa\'s most visually compelling ruins — a complete German colonial diamond-mining town abandoned in 1956, with sand dunes drifting through ballrooms, a bowling alley, and grand mansions preserved by the dry climate.',
        imageUri: KOLMANSKOP_IMAGE,
        price: 'N$380',
        priceSuffix: 'Per person',
        category: 'Culture',
        coordinate: [15.2333, -26.7000],
        geography: { region: 'Karas', town: 'Lüderitz' },
        locationLabel: 'Kolmanskop, 10 km inland from Lüderitz',
        durationLabel: '2 hours',
        groupSizeLabel: 'Any group size',
        tripFit: [
          { label: 'Category', value: 'HISTORY', detail: 'For photographers, history enthusiasts, and anyone who wants something that genuinely stops them in their tracks.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '2 HOURS', detail: 'Morning tours run 09:30 and 11:00 — morning gives the best light inside the buildings.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY', detail: 'Accessible and compelling for any traveler — one of the most memorable stops in Namibia.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [KOLMANSKOP_IMAGE, QUIVER_TREE_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 31, summary: '31 travelers from Germany rated this among their top three Namibia experiences.' },
        booking: { availabilityLabel: 'Tours at 09:30 and 11:00 daily', confirmMode: 'Booked through Namdeb Diamond Corporation', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Licensed site guide', 'Access to all main buildings including the ballroom', 'Photography time inside the structures', 'Lüderitz town context'],
      },
      {
        slug: 'quiver-tree-forest-keetmanshoop',
        badge: 'Botanical Wonder',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Quiver Tree Forest & Giant\'s Playground',
        subtitle: 'Ancient aloe trees at dusk with southern Namibia\'s best stargazing',
        description:
          'A grove of 300-year-old Aloidendron dichotomum trees glowing amber at sunset, paired with the extraordinary dolerite boulder landscape of the Giant\'s Playground 5 km away.',
        imageUri: QUIVER_TREE_IMAGE,
        price: 'N$180',
        priceSuffix: 'Per person',
        category: 'Nature',
        coordinate: [18.1500, -26.9667],
        geography: { region: 'Karas', town: 'Keetmanshoop' },
        locationLabel: '14 km northeast of Keetmanshoop on the D2359',
        durationLabel: '3 hours',
        groupSizeLabel: 'Self-guided or guided',
        tripFit: [
          { label: 'Category', value: 'DUSK + STARS', detail: 'Arrive at golden hour, stay into stargazing — the experience transforms completely after dark.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '3 HOURS', detail: 'Arrive 90 minutes before sunset for the full light sequence.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY SIZE', detail: 'Self-guided entry — works for solo travelers, families, and groups alike.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [QUIVER_TREE_IMAGE, FISH_CANYON_IMAGE],
        travelerMomentum: { countryCode: 'ZA', countryLabel: 'South Africa', visitorCount: 16, summary: '16 travelers from South Africa stopped here on the Cape Town to Windhoek self-drive.' },
        booking: { availabilityLabel: 'Open daily — self-entry from the farm gate', confirmMode: 'Walk-in entry with small fee', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Forest access', 'Giant\'s Playground visit (5 km away)', 'Overnight camping option on the farm', 'Stargazing conditions advisory'],
      },
      {
        slug: 'fish-river-canyon-rim-hike',
        badge: 'Southbound',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Fish River Canyon Rim Hike',
        subtitle: 'Africa\'s largest canyon — guided ridge walk from the Hobas viewpoint',
        description:
          'A southern Namibia day outing for travelers who want scale and silence, with a guided rim route along Africa\'s largest canyon that stretches 160 km and drops up to 550 m deep.',
        imageUri: FISH_CANYON_IMAGE,
        price: 'N$2,050',
        priceSuffix: 'Per person',
        category: 'Adventure',
        coordinate: [17.6942, -27.6278],
        geography: { region: 'Karas', town: 'Fish River Canyon' },
        locationLabel: 'Hobas viewpoint, Fish River Canyon National Park',
        durationLabel: '5 hours',
        groupSizeLabel: 'Up to 8 hikers',
        tripFit: [
          { label: 'Category', value: 'SCENIC HIKE', detail: 'Built for travelers who want one strong landscape day in the far south.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '5 HOURS', detail: 'A solid hiking block without turning into a technical expedition.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 8', detail: 'Small enough to keep the route calm and photo stops easy.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [FISH_CANYON_IMAGE, AI_AIS_IMAGE],
        travelerMomentum: { countryCode: 'CH', countryLabel: 'Switzerland', visitorCount: 4, summary: '4 travelers from Switzerland added this southern detour to their route.' },
        booking: { availabilityLabel: 'Best timing: Early morning departure from Hobas', confirmMode: 'Guide approval within 3 hours', addToTripLabel: 'Add hike to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Guide-led canyon route', 'Trail snacks', 'Transfer from nearby lodges', 'Multiple viewpoint stops including the main lookout'],
      },
      {
        slug: 'ai-ais-hot-springs',
        badge: 'Thermal Springs',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Ai-Ais Hot Springs',
        subtitle: 'Thermal sulphur pools inside the Fish River Canyon — the only resort within the gorge',
        description:
          'Natural hot sulphur springs at the southern end of Fish River Canyon, where the only in-canyon accommodation offers open-air thermal pools against a dramatic rock backdrop.',
        imageUri: AI_AIS_IMAGE,
        price: 'N$680',
        priceSuffix: 'Per person per night',
        category: 'Wellness',
        coordinate: [17.5167, -27.9167],
        geography: { region: 'Karas', town: 'Ai-Ais' },
        locationLabel: 'Ai-Ais Resort, Fish River Canyon National Park',
        durationLabel: 'Overnight',
        groupSizeLabel: 'Any group size',
        tripFit: [
          { label: 'Category', value: 'CANYON RETREAT', detail: 'For travelers who want to slow down inside one of Africa\'s most dramatic landscapes.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'OVERNIGHT', detail: 'Best as a two-night stay — one for the canyon rim, one for recovery in the springs.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY', detail: 'The resort accommodates couples, families, and groups in different room types.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [AI_AIS_IMAGE, FISH_CANYON_IMAGE],
        travelerMomentum: { countryCode: 'ZA', countryLabel: 'South Africa', visitorCount: 13, summary: '13 travelers from South Africa stayed here at the end of the Fish River Canyon 5-day trail.' },
        booking: { availabilityLabel: 'Weekends fill early — book 2+ weeks ahead', confirmMode: 'NWR online reservation', addToTripLabel: 'Add overnight to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Thermal pool access', 'In-canyon accommodation', 'Restaurant and bar on site', 'Proximity to canyon rim viewpoints'],
      },
      {
        slug: 'duwisib-castle',
        badge: 'Colonial Curiosity',
        badgeTone: 'dark',
        ctaLabel: 'Reserve experience',
        title: 'Duwisib Castle',
        subtitle: 'A baronial German colonial castle marooned in the remote Namib south of Maltahöhe',
        description:
          'Built in 1908 by a German cavalry captain and his American wife, then abandoned after World War I — Duwisib Castle sits 72 km from the nearest town, perfectly preserved and entirely unexpected.',
        imageUri: DUWISIB_IMAGE,
        price: 'N$120',
        priceSuffix: 'Entry per person',
        category: 'Culture',
        coordinate: [16.5444, -25.2611],
        geography: { region: 'Hardap', town: 'Maltahöhe' },
        locationLabel: '72 km southwest of Maltahöhe on gravel road',
        durationLabel: '2 hours',
        groupSizeLabel: 'Self-guided or museum tour',
        tripFit: [
          { label: 'Category', value: 'HISTORY', detail: 'For travelers who enjoy the strange traces of colonial history in unexpected Namib settings.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '2 HOURS', detail: 'Castle interior, museum, and farm grounds — best at a relaxed pace.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY', detail: 'Self-guided with informative displays — no minimum group required.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [DUWISIB_IMAGE, SOSSUSVLEI_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 8, summary: '8 travelers from Germany visited as part of the Sossusvlei to Fish River Canyon road.' },
        booking: { availabilityLabel: 'Open daily — self-drive access', confirmMode: 'Walk-in entry', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Castle interior access', 'Museum with original furniture and artefacts', 'Farmland walking', 'Overnight accommodation option'],
      },
      // ── CENTRAL NORTH ─────────────────────────────────────────────────────
      {
        slug: 'cheetah-conservation-fund',
        badge: 'Conservation',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Cheetah Conservation Fund',
        subtitle: 'The world\'s largest cheetah conservation project — guided encounter near Otjiwarongo',
        description:
          'Founded in 1990 on a 100,000-acre research farm, the CCF runs the most comprehensive cheetah conservation program on Earth. Tours include ambassador animal encounters, livestock guarding dog demonstrations, and education centre visits.',
        imageUri: CHEETAH_IMAGE,
        price: 'N$350',
        priceSuffix: 'Per person',
        category: 'Wildlife',
        coordinate: [16.9333, -20.5667],
        geography: { region: 'Otjozondjupa', town: 'Otjiwarongo' },
        locationLabel: '44 km north of Otjiwarongo on the B1',
        durationLabel: '3–4 hours',
        groupSizeLabel: 'Any group size',
        tripFit: [
          { label: 'Category', value: 'CONSERVATION', detail: 'For travelers who want their wildlife encounter rooted in genuine conservation context.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '3–4 HOURS', detail: 'Morning tours at 09:30 are recommended for cheetah activity and cooler temperatures.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'FLEXIBLE', detail: 'Works for families, solo travelers, and groups — the education centre adds depth for all ages.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [CHEETAH_IMAGE, WATERBERG_IMAGE],
        travelerMomentum: { countryCode: 'US', countryLabel: 'United States', visitorCount: 24, summary: '24 travelers from the United States listed this as the most meaningful stop on their Namibia trip.' },
        booking: { availabilityLabel: 'Morning tours at 09:30 — book online in advance', confirmMode: 'CCF online booking', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Ambassador cheetah encounter', 'Livestock guarding dog demonstration', 'Education centre and museum', 'Bush walk option with guide'],
      },
      {
        slug: 'waterberg-plateau-hike',
        badge: 'Plateau Detour',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Waterberg Plateau Guided Walk',
        subtitle: 'Sandstone escarpment views and protected wildlife including white and black rhino',
        description:
          'The Waterberg Plateau rises dramatically from the Otjozondjupa plains — a 250 km² protected plateau with guided walking trails, endemic flora, and populations of white and black rhino, sable antelope, and roan.',
        imageUri: WATERBERG_IMAGE,
        price: 'N$480',
        priceSuffix: 'Per person',
        category: 'Nature',
        coordinate: [17.2833, -20.4667],
        geography: { region: 'Otjozondjupa', town: 'Otjiwarongo' },
        locationLabel: 'Waterberg Plateau Park, 67 km east of Otjiwarongo',
        durationLabel: '2–3 hours',
        groupSizeLabel: 'Up to 8 per guide',
        tripFit: [
          { label: 'Category', value: 'SCENIC WALK', detail: 'For travelers who want altitude, silence, and a landscape that looks completely different from the coast or desert.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '2–3 HOURS', detail: 'Enough to feel the plateau without needing a full overnight commitment.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'UP TO 8', detail: 'Guided walks are mandatory in the park and keep group sizes small.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [WATERBERG_IMAGE, CHEETAH_IMAGE],
        travelerMomentum: { countryCode: 'DE', countryLabel: 'Germany', visitorCount: 6, summary: '6 travelers from Germany rated this the most underrated stop on their Namibia self-drive.' },
        booking: { availabilityLabel: 'Morning walks from 07:30', confirmMode: 'NWR booking at Bernabé de la Bat camp', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Licensed NWR guide', 'Plateau rim views', 'Endemic flora identification', 'Bird list of 200+ plateau species'],
      },
      {
        slug: 'hoba-meteorite-grootfontein',
        badge: 'Cosmic Relic',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Hoba Meteorite',
        subtitle: 'The largest known meteorite on Earth — 60 tonnes of space iron near Grootfontein',
        description:
          'Discovered in 1920 and never moved from its landing site, the Hoba Meteorite is the heaviest naturally occurring piece of iron on Earth — 60 tonnes, 2.7 m × 2.7 m × 0.9 m, composed of 84% iron and 16% nickel.',
        imageUri: HOBA_IMAGE,
        price: 'N$50',
        priceSuffix: 'Entry per person',
        category: 'Nature',
        coordinate: [17.9344, -19.5833],
        geography: { region: 'Otjozondjupa', town: 'Grootfontein' },
        locationLabel: 'Hoba West Farm, 20 km west of Grootfontein',
        durationLabel: '45 minutes',
        groupSizeLabel: 'Any group size',
        tripFit: [
          { label: 'Category', value: 'CURIOSITY STOP', detail: 'For any traveler passing between Etosha and the northeast — requires no prior astronomy interest.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: '45 MIN', detail: 'A tightly contained stop with a big story attached.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY', detail: 'Open access — completely accessible for families, solo travelers, and groups.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [HOBA_IMAGE, ETOSHA_IMAGE],
        travelerMomentum: { countryCode: 'US', countryLabel: 'United States', visitorCount: 11, summary: '11 travelers from the United States called this one of the best 45-minute stops in Africa.' },
        booking: { availabilityLabel: 'Open daily — self-drive access', confirmMode: 'Entry fee at the gate', addToTripLabel: 'Add to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Site access and displays', 'Amphitheatre seating around the meteorite', 'Information boards in multiple languages', 'Picnic area on site'],
      },
      // ── NORTHEAST / CAPRIVI ───────────────────────────────────────────────
      {
        slug: 'popa-falls-divundu',
        badge: 'River Country',
        badgeTone: 'accent',
        ctaLabel: 'Reserve experience',
        title: 'Popa Falls River Camp',
        subtitle: 'Okavango River rapids and lush Caprivi Strip birding at Divundu',
        description:
          'Popa Falls is a series of broad rapids on the Okavango River that marks the gateway to the Caprivi Strip — a complete change of landscape from dry Namibia into lush, riverine green.',
        imageUri: POPA_FALLS_IMAGE,
        price: 'N$420',
        priceSuffix: 'Per night camping',
        category: 'Nature',
        coordinate: [18.2167, -18.0833],
        geography: { region: 'Kavango East', town: 'Divundu' },
        locationLabel: 'Popa Falls Rest Camp, Divundu',
        durationLabel: 'Overnight',
        groupSizeLabel: 'Any group size',
        tripFit: [
          { label: 'Category', value: 'GREEN CORRIDOR', detail: 'For travelers driving east through the Caprivi who want one genuinely atmospheric campsite.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'OVERNIGHT', detail: 'The rapids are best at dawn — an overnight unlocks the full birding and atmosphere window.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: 'ANY', detail: 'Camping and chalets available — works for self-drive couples and groups alike.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [POPA_FALLS_IMAGE, ZAMBEZI_IMAGE],
        travelerMomentum: { countryCode: 'ZA', countryLabel: 'South Africa', visitorCount: 10, summary: '10 travelers from South Africa listed Popa Falls as a favourite Caprivi overnight stop.' },
        booking: { availabilityLabel: 'Camping open year round — chalets may need advance booking', confirmMode: 'NWR booking or walk-in', addToTripLabel: 'Add to Caprivi route', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Campsite or chalet', 'Boardwalk access to the falls', 'Birding guide available on request', 'Morning game drive option into Bwabwata'],
      },
      {
        slug: 'zambezi-houseboat-safari',
        badge: 'River Country',
        badgeTone: 'soft',
        ctaLabel: 'Reserve experience',
        title: 'Zambezi Houseboat Safari',
        subtitle: 'Slow river cruise with hippos, birdlife, and sunset deck dinner on the Zambezi',
        description:
          'End the Namibia route in river country with a slower overnight on the Zambezi, trading dunes for reeds, birdlife, hippos, and a completely different texture of travel in the Caprivi Strip.',
        imageUri: ZAMBEZI_IMAGE,
        price: 'N$3,950',
        priceSuffix: 'Per person',
        category: 'Wildlife',
        coordinate: [24.2741, -17.5039],
        geography: { region: 'Zambezi', town: 'Katima Mulilo' },
        locationLabel: 'Zambezi River Channel near Katima Mulilo',
        durationLabel: 'Overnight',
        groupSizeLabel: 'Cabins for 2 to 10',
        tripFit: [
          { label: 'Category', value: 'RIVER SAFARI', detail: 'Ideal for travelers who want a softer wildlife ending after roads, dunes, and game drives.', icon: 'compass', tone: 'dark' },
          { label: 'Duration', value: 'OVERNIGHT', detail: 'Best as a deliberate final stop rather than a rushed add-on.', icon: 'clock', tone: 'accent' },
          { label: 'Group Size', value: '2 TO 10', detail: 'Flexible for couples, families, or a friend group finishing the route together.', icon: 'users', tone: 'light' },
        ],
        galleryImages: [ZAMBEZI_IMAGE, POPA_FALLS_IMAGE],
        travelerMomentum: { countryCode: 'GB', countryLabel: 'United Kingdom', visitorCount: 5, summary: '5 travelers from the United Kingdom saved this as their river-country finale.' },
        booking: { availabilityLabel: 'Weekend departures available', confirmMode: 'Host confirmation within 6 hours', addToTripLabel: 'Add overnight to trip', continueWithoutTripLabel: 'Book without trip' },
        includes: ['Private cabin', 'Dinner on board', 'Guide-led sunset cruise', 'Morning birding tea', 'Hippo and crocodile viewing from the deck'],
      },
    ];
