export const seedFriendProfiles = [
  {
    travelerSlug: 'local-demo-traveler',
    headline: 'Sunrise chaser with a soft spot for local markets and long road legs.',
    bio: 'Usually building a route around one big landscape moment and a few slower food stops.',
    baseLabel: 'Berlin, Germany',
    destinationLabel: 'Namibia loop',
    travelPace: 'balanced',
    vibe: 'adventure',
    arrivalWindowLabel: 'In Namibia this week',
    interests: ['sunrise hikes', 'markets', 'coffee stops', 'road trips'],
  },
  {
    travelerSlug: 'noah-london',
    headline: 'Photographer planning around dunes, wildlife, and cleaner morning light.',
    bio: 'Happy to leave early if it buys us better shadows and fewer crowds at the stops.',
    baseLabel: 'London, United Kingdom',
    destinationLabel: 'Namibia loop',
    travelPace: 'fast',
    vibe: 'adventure',
    arrivalWindowLabel: 'Arrives tomorrow',
    interests: ['photography', 'dunes', 'sunrise hikes', '4x4 routes'],
  },
  {
    travelerSlug: 'sofia-lisbon',
    headline: 'Warm social energy, coastal detours, and dinner plans that actually happen.',
    bio: 'I like building a route that keeps one big adventure and one beautiful meal in play each day.',
    baseLabel: 'Lisbon, Portugal',
    destinationLabel: 'Namibia coast + dunes',
    travelPace: 'balanced',
    vibe: 'social',
    arrivalWindowLabel: 'Free for the next 5 days',
    interests: ['food spots', 'coastal drives', 'sunset drinks', 'markets'],
  },
  {
    travelerSlug: 'elias-windhoek',
    headline: 'Local anchor for fuel stops, road timing, and the spots worth the extra turnoff.',
    bio: 'Usually the one keeping the route realistic while still finding room for the good scenic nonsense.',
    baseLabel: 'Windhoek, Namibia',
    destinationLabel: 'Namibia loop',
    travelPace: 'balanced',
    vibe: 'culture',
    arrivalWindowLabel: 'Open this weekend',
    interests: ['local food', 'hidden turnoffs', 'wildlife', 'road trips'],
  },
  {
    travelerSlug: 'anna-berlin',
    headline: 'Adventure-heavy days with enough reset time to still enjoy the evenings.',
    bio: 'Down for sandboarding, coast air, and any route that ends somewhere design-forward and quiet.',
    baseLabel: 'Berlin, Germany',
    destinationLabel: 'Swakopmund and dunes',
    travelPace: 'balanced',
    vibe: 'adventure',
    arrivalWindowLabel: 'Available this weekend',
    interests: ['sandboarding', 'design stays', 'coffee stops', 'ocean walks'],
  },
  {
    travelerSlug: 'luc-amsterdam',
    headline: 'Road-trip optimist with too many saved maps and an excellent snack tolerance.',
    bio: 'I like seeing a lot in one loop, but I still want the route to feel cinematic instead of rushed.',
    baseLabel: 'Amsterdam, Netherlands',
    destinationLabel: 'Namibia northbound loop',
    travelPace: 'fast',
    vibe: 'social',
    arrivalWindowLabel: 'Can join in 2 days',
    interests: ['road trips', 'wildlife', 'photo stops', 'live music'],
  },
  {
    travelerSlug: 'maya-new-york',
    headline: 'Food-led traveler who still wants one big story each day.',
    bio: 'Usually building around café mornings, local guides, and the kind of places that make good voice notes.',
    baseLabel: 'New York, United States',
    destinationLabel: 'Windhoek + coast',
    travelPace: 'slow',
    vibe: 'food',
    arrivalWindowLabel: 'Landing tonight',
    interests: ['food spots', 'coffee stops', 'markets', 'walking tours'],
  },
  {
    travelerSlug: 'max-vienna',
    headline: 'Quiet logistics brain, big fan of dramatic landscapes and well-timed overnight stops.',
    bio: 'Best in a crew when someone needs to actually turn a loose idea into a route that works.',
    baseLabel: 'Vienna, Austria',
    destinationLabel: 'Namibia loop',
    travelPace: 'balanced',
    vibe: 'relaxation',
    arrivalWindowLabel: 'Free after Friday',
    interests: ['stargazing', 'lodges', 'road trips', 'desert nights'],
  },
  {
    travelerSlug: 'chloe-melbourne',
    headline: 'Coast-first planner who likes a softer pacing and strong place recommendations.',
    bio: 'Give me one huge landscape, one slow breakfast, and one friend who remembers the playlists.',
    baseLabel: 'Melbourne, Australia',
    destinationLabel: 'Walvis Bay + Swakopmund',
    travelPace: 'slow',
    vibe: 'relaxation',
    arrivalWindowLabel: 'Can join mid-week',
    interests: ['lagoon mornings', 'wellness stays', 'sunset walks', 'coffee stops'],
  },
  {
    travelerSlug: 'james-toronto',
    headline: 'Wildlife-first traveler who does not mind a very early start if the sightings are worth it.',
    bio: 'I usually travel with binoculars, one camera, and a route pinned down before breakfast.',
    baseLabel: 'Toronto, Canada',
    destinationLabel: 'Etosha extension',
    travelPace: 'fast',
    vibe: 'adventure',
    arrivalWindowLabel: 'Available next week',
    interests: ['wildlife', 'game drives', 'photography', 'road trips'],
  },
] as const;
